import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Headers } from "./components";
import { StoreProvider } from "./store/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
    <html lang="en">
      <body className={inter.className}>
        <Headers/>
        <div className="mx-10 mt-10"> {children}</div>
       
      </body>
    </html>
    </StoreProvider>
  );
}
